import test from 'node:test';
import assert from 'node:assert/strict';
import {programFixture,stamp} from './helpers/refund-program-fixture.mjs';
import {refundProgramFacts} from '../src/refund-program.mjs';
import {reconcileRefundInventory,refundHistory} from '../src/refund-reconciliation.mjs';
import {digest} from '../src/payments.mjs';
import {transition} from '../src/refund-application.mjs';
import {assessRefundEligibility} from '../src/refund-eligibility.mjs';
const facts=h=>refundProgramFacts(h.state,h.a,h.p.id,h.at);
for(const count of [1,2,3])test(`${count} whole units refund exact frozen amount and retire once`,()=>{
 const h=programFixture(),before=structuredClone(h.state),o=h.intent(count);assert.equal(o.amountMinor,count*2000);h.dispatch(o);h.observe(o,'completed');h.observe(o,'completed');
 assert.equal(h.state.creditUnits.filter(u=>u.status==='refunded').length,count);assert.equal(h.state.creditEvents.filter(e=>e.type==='refund_retire').length,count);
 for(const k of ['purchaseDrafts','paymentAttempts','entitlementIssuances','passes','reservations'])assert.deepEqual(h.state[k],before[k]);
 assert.equal(facts(h).remainingBusinessMinor,(3-count)*2000);
});
test('multiple completed partial refunds exhaust value without over-refund',()=>{const h=programFixture();for(let i=0;i<3;i++){const o=h.intent();h.dispatch(o);h.observe(o,'completed');}assert.equal(h.state.refundOperations.length,3);assert.equal(h.state.refundOperations.reduce((n,o)=>n+o.amountMinor,0),6000);assert.throws(()=>h.intent(),/NO_REFUNDABLE/);});
test('duplicate request retains stable operation and idempotency identity',()=>{const h=programFixture(),body={requestId:'same',unitIds:[h.state.creditUnits[0].id]},o=h.run('intent',body);assert.deepEqual(h.run('intent',body),o);assert.throws(()=>h.run('intent',{...body,reason:'other'}),/conflict/);assert.equal(h.state.refundOperations.length,1);});
test('a competing intent cannot reuse held units or start a second payment refund',()=>{const h=programFixture(),e=h.evidence();h.intent();assert.throws(()=>h.run('intent',{unitIds:[h.state.creditUnits[1].id]},e),/Fresh business/);assert.throws(()=>h.intent(),/OWNED_INTENT_PENDING/);});
test('used credits remain spent and only remaining unused value is refundable',()=>{const h=programFixture();h.consume();assert.equal(facts(h).remainingBusinessMinor,4000);const o=h.intent(2);h.dispatch(o);h.observe(o,'completed');assert.equal(h.state.creditUnits[0].status,'spent');assert.equal(h.state.creditEvents.filter(e=>e.type==='consume').length,1);});
test('restored unit substitutes for original value without rewriting usage',()=>{const h=programFixture();h.consume(true);const prior=structuredClone(h.state.creditEvents),o=h.intent(3);assert.equal(o.amountMinor,6000);h.dispatch(o);h.observe(o,'completed');assert.equal(h.state.creditUnits[0].status,'spent');assert.equal(h.state.creditUnits.filter(u=>u.status==='refunded').length,3);assert.deepEqual(h.state.creditEvents.slice(0,prior.length),prior);});
for(const [name,change,code] of [
 ['active reservation',h=>h.state.reservations.push({participantId:h.p.participantId,status:'reserved'}),'ACTIVE_OR_UNRESOLVED'],
 ['unresolved reservation',h=>h.state.reservations.push({participantId:h.p.participantId,status:'unknown'}),'ACTIVE_OR_UNRESOLVED'],
 ['fractional allocation',h=>h.p.totalMinor=6001,'FROZEN_ALLOCATION'],
 ['amended terms',h=>h.p.amendments=[{}],'FROZEN_ALLOCATION'],
 ['forged terms',h=>h.p.terms.productName='changed','PURCHASE_PAYMENT'],
 ['missing issue proof',h=>h.state.creditEvents.shift(),'ORIGIN_PROOF'],
 ['missing consumption',h=>{h.consume();h.state.creditEvents=h.state.creditEvents.filter(e=>e.type!=='consume');},'CONSUMPTION_PROOF'],
 ['forged restoration',h=>{h.consume(true);h.state.reservations[0].restoredCreditUnitId='wrong';},'RESTORATION_PROOF'],
 ['corrected restoration',h=>{h.consume(true);h.state.reservations[0].cancellationHistory.push({action:'correction'});},'RESTORATION_PROOF'],
 ['restoration reversal',h=>{h.consume(true);h.state.creditEvents.push({id:'reverse',type:'reverse_restoration',unitId:'restored'});},'UNSUPPORTED_OR_INVALID'],
 ['consumed restored unit',h=>{h.consume(true);h.state.creditEvents.push({id:'consume2',type:'consume',unitId:'restored',passId:h.state.passes[0].id,participantId:h.p.participantId,createdAt:stamp});},'RESTORATION_PROOF'],
 ['unproven retired credit',h=>h.state.creditUnits[0].status='refunded','REFUND_DISPOSITION'],
])test(`blocks ${name}`,()=>{const h=programFixture();change(h);assert.equal(facts(h).status,'blocked');assert.match(facts(h).reasonCodes.join(','),new RegExp(code));});
test('cutoff is exclusive without changing frozen terms or closed assessment',()=>{const h=programFixture(),terms=digest(h.p.terms),end=Date.parse(h.p.refundWindowStartsAt)+30*86400000;h.at=new Date(end-1).toISOString();assert.equal(facts(h).status,'ready');for(const delta of [0,1]){h.at=new Date(end+delta).toISOString();assert.equal(facts(h).reasonCodes[0],'REFUND_CUTOFF_REACHED');}assert.equal(digest(h.p.terms),terms);assert.ok(assessRefundEligibility({state:h.state,authority:h.a,purchaseId:h.p.id,at:new Date(end).toISOString(),refundRecords:[]}).reasonCodes.includes('REFUND_CUTOFF_POLICY_UNRESOLVED'));});
for(const status of ['unknown','pending','failed','rejected'])test(`${status} keeps hold and blocks repeated dispatch`,()=>{const h=programFixture(),o=h.intent();h.dispatch(o);h.observe(o,status);assert.equal(h.state.creditUnits[0].status,'refund_held');assert.throws(()=>h.dispatch(o),/already claimed/);if(['failed','rejected'].includes(status)){h.run('release',{operationId:o.id},h.outcome(o,status));h.run('release',{operationId:o.id},h.outcome(o,status));assert.equal(h.state.activity.filter(e=>e.action==='refund-hold-released').length,1);}else assert.throws(()=>h.run('release',{operationId:o.id},h.outcome(o,status)));});
test('unknown cannot replace a terminal completed outcome',()=>{const h=programFixture(),o=h.intent();h.dispatch(o);h.observe(o,'completed');assert.throws(()=>h.observe(o,'unknown'),/Terminal/);});
test('held unit cannot be used and participant cannot reserve',()=>{const h=programFixture();h.intent();assert.throws(()=>transition(h.state,{action:'reserve',body:{participantId:h.p.participantId,requestId:'book'}},h.a),/held/);});
for(const role of ['member','unknown'])test(`${role} cannot mutate refunds`,()=>{const h=programFixture();assert.throws(()=>h.run('intent',{unitIds:[h.state.creditUnits[0].id]},h.evidence(),{...h.a,role}),/Staff/);});
test('foreign business cannot read candidate facts or mutate',()=>{const h=programFixture(),a={...h.a,businessId:'foreign'};assert.equal(refundProgramFacts(h.state,a,h.p.id,h.at).status,'blocked');assert.throws(()=>h.run('intent',{},h.evidence(),a),/unavailable/);});
test('second business and second processor use identical generic rules',()=>{const h=programFixture();h.state=JSON.parse(JSON.stringify(h.state).replaceAll('vega-development','business-two-tenant').replaceAll('vega-dance-lab','business-two').replaceAll('square','processor-two'));h.a.tenantId='business-two-tenant';h.a.businessId='business-two';h.state.paymentAttempts[0].offerDigest=digest(h.p.terms);assert.equal(facts(h).status,'ready');const o=h.intent();h.dispatch(o);h.observe(o,'completed');assert.equal(o.amountMinor,2000);});
test('deterministic facts and comparison preserve inputs and closed assessment output',()=>{const h=programFixture(),before=structuredClone(h.state),i=h.inventory(),old=assessRefundEligibility({state:h.state,authority:h.a,purchaseId:h.p.id,at:stamp,refundRecords:[]});assert.deepEqual(facts(h),facts(h));assert.deepEqual(reconcileRefundInventory({purchase:h.purchase(),operations:[],evidence:i,at:stamp}),reconcileRefundInventory({purchase:h.purchase(),operations:[],evidence:i,at:stamp}));assert.deepEqual(h.state,before);assert.deepEqual(old,assessRefundEligibility({state:h.state,authority:h.a,purchaseId:h.p.id,at:stamp,refundRecords:[]}));});
function external(h,status='completed',amount=2000){h.extra=[{id:'external',paymentId:h.purchase().paymentId,status,amountMinor:amount,currency:'USD',reason:'Dashboard'}];}
test('external refund holds all available rights; explicit exact allocation retires one and releases others',()=>{const h=programFixture();external(h);h.run('external');const o=h.state.refundOperations[0];assert.equal(o.status,'needs-review');assert.equal(h.state.creditUnits.filter(u=>u.status==='refund_held').length,3);h.extra=[];h.run('external-resolve',{operationId:o.id,unitIds:[h.state.creditUnits[0].id]});assert.equal(h.state.creditUnits.filter(u=>u.status==='refunded').length,1);assert.equal(h.state.creditUnits.filter(u=>u.status==='available').length,2);assert.throws(()=>h.dispatch(o));});
for(const status of ['failed','rejected'])test(`external ${status} requires fresh review before release`,()=>{const h=programFixture();external(h,status);h.run('external');const o=h.state.refundOperations[0];h.extra=[];h.run('external-resolve',{operationId:o.id});assert.equal(h.state.creditUnits.filter(u=>u.status==='available').length,3);});
test('external pending or unallocatable amount remains held for review',()=>{for(const [status,amount] of [['pending',2000],['completed',1500]]){const h=programFixture();external(h,status,amount);h.run('external');const o=h.state.refundOperations[0];h.extra=[];assert.throws(()=>h.run('external-resolve',{operationId:o.id,unitIds:[h.state.creditUnits[0].id]}));assert.equal(h.state.creditUnits.filter(u=>u.status==='refund_held').length,3);}});
test('lost response can bind only a unique staff-reviewed match, then reconcile without dispatch',()=>{const h=programFixture(),o=h.intent();h.dispatch(o);h.run('observe',{operationId:o.id},{...h.outcome(o,'unknown'),refundId:undefined});h.extra=[{id:'found',paymentId:o.paymentId,amountMinor:o.amountMinor,currency:o.currency,status:'completed',reason:`Refund ${o.id}: ${o.reason}`}];h.run('bind',{operationId:o.id});assert.equal(h.state.refundOperations[0].providerRefundId,'found');h.run('observe',{operationId:o.id},{...h.outcome(o,'completed'),refundId:'found'});assert.equal(h.state.creditUnits.filter(u=>u.status==='refunded').length,1);});
test('no provider match never permits resubmission or release',()=>{const h=programFixture(),o=h.intent();h.dispatch(o);h.run('observe',{operationId:o.id},{...h.outcome(o,'unknown'),refundId:undefined});assert.throws(()=>h.run('bind',{operationId:o.id}),/Unique/);assert.throws(()=>h.dispatch(o));});
test('member history never exposes provider evidence, staff reasons or other buyers',()=>{const h=programFixture(),o=h.intent(),a={...h.a,role:'member',userId:h.p.buyerId,participantIds:[h.p.participantId]};const rows=refundHistory(h.state,a);assert.equal(rows.length,1);for(const key of ['reason','providerKey','providerRefundId','actorId','readiness','policy','integrationRef'])assert.ok(!JSON.stringify(rows).includes(`"${key}"`));assert.deepEqual(refundHistory(h.state,{...a,userId:'other'}),[]);assert.deepEqual(refundHistory(h.state,{...a,businessId:'foreign'}),[]);});
