import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {createApplicationApi} from '../src/runtime/refund-application-api.mjs';
import {ApplicationError} from '../src/application.mjs';
import {refundProgramUI} from '../public/refund-ui.js';
const env={VEGA_ENV:'development',VEGA_EXTERNAL_EFFECTS:'disabled',SUPABASE_URL:'https://cjdoczrxcjynjhgpgqop.supabase.co',SUPABASE_PUBLISHABLE_KEY:'synthetic'};
async function call(path,store,body,auth=true){let status,value;const api=createApplicationApi(env,store,async url=>{assert.equal(url,env.SUPABASE_URL+'/auth/v1/user');return {ok:true,json:async()=>({id:'4c3dcc3b-34cf-4664-bdf5-e16bbd6cd124'})};});const req=Readable.from(body?[Buffer.from(JSON.stringify(body))]:[]);Object.assign(req,{url:path,method:body?'POST':'GET',headers:{...(auth?{authorization:'Bearer synthetic'}:{}),'content-type':'application/json'}});await api(req,{writeHead(s){status=s;},end(v){value=JSON.parse(v);}});return {status,value};}
for(const action of ['prepare','execute'])test(`program API ${action} remains disabled with no store/provider effect`,async()=>{const r=await call(`/api/commerce/refund-program/${action}`,{refundContext(){assert.fail('store read');}},{purchaseId:'purchase',requestId:'r'});assert.equal(r.status,503);assert.match(r.value.error,/disabled/);});
for(const action of ['reconcile','release','external','resolve','bind'])test(`program API ${action} checks current staff scope before provider reads`,async()=>{let reads=0;const r=await call(`/api/commerce/refund-program/${action}`,{refundContext(){reads++;throw new ApplicationError('Staff access required',403);}},{purchaseId:'purchase',requestId:'r'});assert.equal(r.status,403);assert.equal(reads,1);});
test('read-only provider comparison denies member before provider acquisition',async()=>{const r=await call('/api/commerce/purchases/3609b576-10f1-4d16-94df-e46e10ec7a96/refund-reconciliation',{refundContext(){throw new ApplicationError('Staff access required',403);}});assert.equal(r.status,403);});
test('unauthenticated program routes cannot load business state',async()=>{const r=await call('/api/commerce/refund-program/external',{refundContext(){assert.fail();}},{purchaseId:'p',requestId:'r'},false);assert.equal(r.status,401);});
test('member history renders outcomes without staff actions',()=>{const html=refundProgramUI({getData:()=>({context:{role:'member'},refundHistory:[{id:'o',purchaseId:'p',status:'completed',amountMinor:2000,currency:'USD',entitlementDisposition:'retired',history:[{event:'refund-observation',at:'2026-10-05',status:'completed'}]}]}),escape:String}).render();assert.match(html,/Your refunds/);assert.match(html,/retired/);assert.doesNotMatch(html,/data-refund-program|providerKey|Refund management/);});
test('staff sees complete operation history and recovery controls while submission stays disabled',()=>{const html=refundProgramUI({getData:()=>({context:{role:'staff'},purchaseDrafts:[{id:'p',paymentStatus:'succeeded',totalMinor:6000,currency:'USD'}],refundProgram:{enabled:false},refundHistory:[{id:'o',purchaseId:'p',contract:'refund-program/1',origin:'staff',status:'pending',amountMinor:2000,currency:'USD',entitlementDisposition:'held',history:[]}]}),escape:String}).render();assert.match(html,/Refund execution is disabled/);assert.match(html,/Check refund readiness/);assert.match(html,/<button disabled>Submit this refund once/);});
