import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {baseline,policies,sha,validateEnvironment,verifyReads,readCheckpoint,checkpointSql} from '../scripts/refund-source-job-checks.mjs';
const env={VEGA_ENV:'development',VEGA_EXTERNAL_EFFECTS:'disabled',VEGA_SANDBOX_PAYMENT_EXECUTION:'disabled',SUPABASE_URL:'https://cjdoczrxcjynjhgpgqop.supabase.co',RENDER_GIT_COMMIT:'a'.repeat(40),VEGA_REFUND_VERIFY_COMMIT:'a'.repeat(40),APP_DATABASE_URL:'test-only'};
test('runtime gate accepts only the pinned Development build with execution disabled',()=>assert.equal(validateEnvironment(env,[]),'a'.repeat(40)));
for(const key of ['VEGA_ENV','VEGA_EXTERNAL_EFFECTS','VEGA_SANDBOX_PAYMENT_EXECUTION','SUPABASE_URL','RENDER_GIT_COMMIT','VEGA_REFUND_VERIFY_COMMIT','NODE_OPTIONS','NODE_PATH'])test(`runtime rejects ${key} drift`,()=>assert.throws(()=>validateEnvironment({...env,[key]:'unauthorized'},[])));
test('no command-line target or SQL overrides',()=>assert.throws(()=>validateEnvironment(env,['--purchase','other'])));
test('missing connection rejected before pg initialization',()=>assert.throws(()=>validateEnvironment({...env,APP_DATABASE_URL:undefined},[])));
const checkpoint=()=>({...baseline,componentDigest:'b'.repeat(64),commandsDigest:'c'.repeat(32),recoveryDigest:'d'.repeat(32),membersDigest:'e'.repeat(32),integrationsDigest:'f'.repeat(32)});
function assessment(){
 const ownedSnapshot={state:{synthetic:true},facts:{synthetic:true}};
 return {status:'blocked',executionAuthorized:false,checkpoint:{stateDigest:baseline.canonicalStateSha256},assessment:{status:'blocked',coverage:{provider:'provider_unknown'}},assemblerInput:{ownedSnapshot,frozenTermsRef:{digest:baseline.frozenTermsSha256},attestations:{coverage:{provider:{state:'provider_unknown'},owned:{refunds:{state:'incomplete'}}},policyBoundaries:[...policies],snapshot:{payloadDigest:sha(ownedSnapshot)}}}};
}
function setup(){const calls=[];return {calls,read:async()=>{calls.push('read');return checkpoint();},load:async s=>{calls.push(s.label);return s.label==='staff'?assessment():{status:'denied',executionAuthorized:false};}};}
test('bounded orchestration compares before/after and all five authorization probes',async()=>{const x=setup(),r=await verifyReads(x);assert.deepEqual(x.calls,['read','staff','member','missing-purchase','foreign-business','foreign-tenant','read']);assert.deepEqual(r.before,r.after);assert.equal(r.independentReconciliationRequired,true);assert.equal(r.executionAuthorized,false);assert.equal(r.provider,'provider_unknown');assert.equal(r.owned,'incomplete');});
for(const key of Object.keys(baseline))test(`baseline ${key} drift stops before adapter reads`,async()=>{const x=setup();x.read=async()=>({...checkpoint(),[key]:'changed'});await assert.rejects(verifyReads(x));assert.deepEqual(x.calls,[]);});
test('any observed post-read record change prevents success evidence',async()=>{let n=0;const x=setup();x.read=async()=>({...checkpoint(),commandsDigest:++n===1?'c'.repeat(32):'d'.repeat(32)});await assert.rejects(verifyReads(x));});
for(const mutate of [r=>r.executionAuthorized=true,r=>r.assemblerInput.attestations.coverage.provider.state='complete_as_of',r=>r.assessment.coverage.provider='complete_as_of',r=>r.assemblerInput.attestations.coverage.owned.refunds.state='complete',r=>r.assemblerInput.attestations.policyBoundaries=[],r=>r.assemblerInput.attestations.snapshot.payloadDigest='0'.repeat(64),r=>r.assemblerInput.frozenTermsRef.digest='0'.repeat(64)])test('reject unsafe chain result',async()=>{const x=setup();x.load=async()=>{const r=assessment();mutate(r);return r;};await assert.rejects(verifyReads(x));});
test('cross-scope denial carrying snapshot data fails verification',async()=>{const x=setup(),load=x.load;x.load=async s=>s.label==='staff'?load(s):{status:'denied',executionAuthorized:false,assemblerInput:{secret:true}};await assert.rejects(verifyReads(x));});
test('independent checkpoint failure rolls back and discards connection without retry',async()=>{const calls=[];const pool={connect:async()=>({query:async sql=>{calls.push(sql);if(sql!=='ROLLBACK')throw new Error('secret driver detail');},release:x=>calls.push(x)})};await assert.rejects(readCheckpoint(pool));assert.deepEqual(calls,[checkpointSql,'ROLLBACK',true]);assert.match(checkpointSql,/^BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;/);assert.match(checkpointSql,/ROLLBACK;\s*$/);assert.doesNotMatch(checkpointSql,/\b(INSERT|UPDATE|DELETE|TRUNCATE|GRANT|REVOKE)\b/i);});
test('runner has no provider client or HTTP server entrypoint',()=>{const text=readFileSync(new URL('../scripts/verify-refund-source-job.mjs',import.meta.url),'utf8');assert.doesNotMatch(text,/start-web|fetch\(|createServer|createDirectPayments|createApplicationDatabase\(/);assert.match(text,/110000/);assert.match(text,/default_transaction_read_only=on/);assert.match(text,/statement_timeout:10000/);});
