import test from 'node:test';
import assert from 'node:assert/strict';
import {programFixture} from './helpers/refund-program-fixture.mjs';
import {createRefundProgram} from '../src/runtime/refund-program-workflow.mjs';
import {digest} from '../src/payments.mjs';
function setup(){const h=programFixture();let calls=0,n=0;const x={h,status:'completed',ack:true,enabled:true,throwSubmit:false,throwCommit:false};
 const store={refundContext:async(u,p,id)=>({purchase:h.purchase(),stateDigest:digest(h.state),operation:h.state.refundOperations?.find(o=>o.id===id),operations:h.state.refundOperations??[]}),operation:async()=>({pending:!x.ack,independentReceipt:{state:x.ack?'acknowledged':'pending'}}),refundCommand:async(u,c,e)=>{const o=h.run(c.action.replace('refund-program-',''),c.body,e);if(c.action.endsWith('-dispatch')&&x.throwCommit)throw Error('lost commit acknowledgment');return {refund:o,independentReceipt:{operationId:'outbox'}};}};
 const adapter={inventory:async()=>h.inventory(),submitProgram:async o=>{calls++;if(x.throwSubmit)throw Error('lost response');return h.outcome(o,x.status);},inspectProgram:async o=>h.outcome(o,x.status)};
 x.program=createRefundProgram({store,adapter,enabled:()=>x.enabled,id:()=>`${++n}`,now:()=>h.at});x.body=()=>({purchaseId:h.p.id,requestId:'intent',reason:'Customer request',unitIds:[h.state.creditUnits[0].id]});Object.defineProperty(x,'calls',{get:()=>calls});return x;}
test('coordinator submits exactly once under concurrent execute and keeps stable key',async()=>{const x=setup(),r=await x.program.prepare('staff',x.body()),b={purchaseId:x.h.p.id,operationId:r.refund.id,requestId:'execute'};const results=await Promise.allSettled([x.program.execute('staff',b),x.program.execute('staff',b)]);assert.equal(x.calls,1);assert.ok(results.some(r=>r.status==='fulfilled'));assert.equal(x.h.state.refundOperations[0].status,'completed');await x.program.execute('staff',b);assert.equal(x.calls,1);});
test('lost provider response retains hold; replay cannot resubmit',async()=>{const x=setup(),r=await x.program.prepare('staff',x.body()),b={purchaseId:x.h.p.id,operationId:r.refund.id,requestId:'execute'};x.throwSubmit=true;await x.program.execute('staff',b);await x.program.execute('staff',b);assert.equal(x.calls,1);assert.equal(x.h.state.refundOperations[0].status,'unknown');assert.equal(x.h.state.creditUnits[0].status,'refund_held');});
test('lost dispatch commit acknowledgment submits zero times, replay reconciles only',async()=>{const x=setup(),r=await x.program.prepare('staff',x.body()),b={purchaseId:x.h.p.id,operationId:r.refund.id,requestId:'execute'};x.throwCommit=true;await assert.rejects(x.program.execute('staff',b));await x.program.execute('staff',b);assert.equal(x.calls,0);});
test('recovery acknowledgment is required before submission',async()=>{const x=setup(),r=await x.program.prepare('staff',x.body());x.ack=false;await assert.rejects(x.program.execute('staff',{purchaseId:x.h.p.id,operationId:r.refund.id,requestId:'execute'}),/acknowledgment/);assert.equal(x.calls,0);});
test('disabled gate prevents new intents/submission but permits recovery checks',async()=>{const x=setup(),r=await x.program.prepare('staff',x.body()),b={purchaseId:x.h.p.id,operationId:r.refund.id,requestId:'execute'};x.status='pending';await x.program.execute('staff',b);x.enabled=false;await assert.rejects(x.program.prepare('staff',x.body()),/disabled/);await assert.rejects(x.program.execute('staff',b),/disabled/);x.status='completed';await x.program.reconcile('staff',b);assert.equal(x.calls,1);assert.equal(x.h.state.refundOperations[0].status,'completed');});
test('request cannot inject evidence, policy or amount',async()=>{const x=setup();for(const key of ['evidence','policy','amountMinor'])await assert.rejects(x.program.prepare('staff',{...x.body(),[key]:'forged'}),/Invalid/);assert.equal(x.calls,0);});
